apiVersion: v1
kind: Service
metadata:
  name: tcp-udp-router-service
  namespace: tcp-udp-router
  labels:
    app: tcp-udp-router
spec:
  type: ClusterIP
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: http
  - port: 4000
    targetPort: 4000
    protocol: TCP
    name: tcp
  - port: 5000
    targetPort: 5000
    protocol: UDP
    name: udp
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: health
  - port: 3001
    targetPort: 3001
    protocol: TCP
    name: metrics
  selector:
    app: tcp-udp-router
---
apiVersion: v1
kind: Service
metadata:
  name: tcp-udp-router-loadbalancer
  namespace: tcp-udp-router
  labels:
    app: tcp-udp-router
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
  - port: 4000
    targetPort: 4000
    protocol: TCP
    name: tcp
  - port: 5000
    targetPort: 5000
    protocol: UDP
    name: udp
  selector:
    app: tcp-udp-router