name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:  # Manuel tetikleme

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20

    - name: Install dependencies
    - name: Run tests
      run: npm test

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_PAT }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: Dockerfile
        push: true
        tags: |
          ghcr.io/wkerwmm/tcpudprouter:latest
          ghcr.io/wkerwmm/tcpudprouter:${{ github.sha }}
        cache-from: type=registry,ref=ghcr.io/wkerwmm/tcpudprouter:latest
        cache-to: type=registry,mode=max,ref=ghcr.io/wkerwmm/tcpudprouter:cache
